import type { AppProps } from "next/app";
import GlobalStyle from "@/utils/styled-component/Globalstyle";
import { ThemeProvider } from "styled-components";
import theme from "@/styles/theme";
import Layout from "@/components/layout/Layout";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>首頁</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/i_logo.png" />
      </Head>

      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ThemeProvider>
    </>
  );
}
