import type { AppProps } from "next/app";
import GlobalStyle from "@/utils/styled-component/Globalstyle";
import { ThemeProvider } from "styled-components";
import theme from "@/styles/theme";
import Head from "next/head";
import store from "@/utils/redux/store";
import { Provider } from "react-redux";
import AuthProvider from "@/components/auth/AuthProvider";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Loading from "@/components/ui/Loading";

export default function App({ Component, pageProps }: AppProps) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const handleStart = () => setLoading(true);
    const handleComplete = () => setLoading(false);

    router.events.on("routeChangeStart", handleStart);
    router.events.on("routeChangeComplete", handleComplete);
    router.events.on("routeChangeError", handleComplete);

    return () => {
      router.events.off("routeChangeStart", handleStart);
      router.events.off("routeChangeComplete", handleComplete);
      router.events.off("routeChangeError", handleComplete);
    };
  }, [router]);

  return (
    <Provider store={store}>
      <Head>
        <title>首頁</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/LOGO.webp" />
      </Head>
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        {loading && <Loading />}
        <AuthProvider>
          <Component {...pageProps} />
        </AuthProvider>
      </ThemeProvider>
    </Provider>
  );
}
